version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pixel-fox-app
    volumes:
      - ./src:/var/www/html
    networks:
      - pixel-fox
    depends_on:
      - db
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: pixel-fox-nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - pixel-fox

  db:
    image: mysql:8.0
    container_name: pixel-fox-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pixel_fox
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_USER: USERNAME
      MYSQL_PASSWORD: PASSWORD
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - pixel-fox

volumes:
  dbdata:

networks:
  pixel-fox:
